### ISSUE TITLE
README instructions for building not working

### ISSUE THREAD

**Issue by stblassitude** [fffonion/kvm-github-actions-runner#1]
I've tried to follow the instructions in the README to build the images, but:
* there is no branch `kvm` in https://github.com/fffonion/runner-images-kvm
* there is no file `images/linux/ubuntu2404.pkr.hcl`

I tried poking around in runner-images-kvm, but could not immediately see which Packer file would build an Ubuntu image on KVM.

**Comment by fffonion** [comment]
@stblassitude please see the tags https://github.com/fffonion/runner-images-kvm/tags instead of the `kvm` branch.

**Comment by stblassitude** [comment]
Thank you, but I'm still not sure how to start a build successfully:
```
~/runner-images-kvm/images/ubuntu/templates# packer build ./ubuntu-22.04.pkr.hcl 
Error: no plugin installed for github.com/hashicorp/azure 1.4.5

Did you run packer init for this project ?
```

**Comment by fffonion** [comment]
Yes, need to run `packer init` once

**Comment by stblassitude** [comment]
Ah yes, thank you! This seems to do the trick:
```
cd runner-images-kvm
git fetch --tags
git checkout ubuntu24/20240714.1
cd images/ubuntu/templates
packer init ubuntu-22.04.pkr.hcl
packer build ubuntu-22.04.pkr.hcl
```
(I probably should build ubunt 24.04 from that tag, but the 22.04 build is still progressing. I'll do that one afterwards.)

**Comment by stblassitude** [comment]
22.04 did not build from that tag, but 24.04 did. Thank you for your help!
